<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dotnet07-PC" ignored="0" name="testing" tests="2" failures="1" timestamp="12 Jul 2018 17:21:37 GMT" time="43.245" errors="0">
  <testcase name="verifyAssignTrimmingTask" time="19.835" classname="thingblu.TestsCasesManager.assignTrimmingTask">
    <failure type="java.lang.AssertionError" message="expected [Lot details saved successfully.] but found [Task Assigned Successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Lot details saved successfully.] but found [Task Assigned Successfully.]
	at thingblu.TestsCasesManager.assignTrimmingTask.verifyAssignTrimmingTask(assignTrimmingTask.java:30)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAssignTrimmingTask -->
  <testcase name="getStatusTablist" time="9.429" classname="thingblu.TestsCasesManager.CompleteTask"/>
</testsuite> <!-- testing -->
